### ISSUE TITLE
找不到模組 './dialog' 或其對應的型別宣告。

### ISSUE THREAD

**Issue by haha861924** [willy874/bam-ui#1]
![image](https://user-images.githubusercontent.com/40877568/151763191-dfaff9d6-c59e-4678-8037-92f11e6c4b3b.png)

如圖，我照搬了 DialogView.vue 的組件，會出現找不到 `'./dialog` 的錯誤訊息。
請問還需要增加什麼嗎?

**Comment by huibizhang** [comment]
@haha861924 你把 `"./dialog"` 改成 `"bam-ui"` 試試看

照理來說他的 `DialogView.vue` 那份應該是他套件內部的內容

**Comment by willy874** [comment]
是我這邊打錯了，兔兔說的沒錯，要調整成套件內部。
我現在重新調整套件專案結構，會重新修正文件。

**Comment by haha861924** [comment]
了解　謝謝 @huibizhang 兔兔協助!
謝謝竹主老師~
